#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./create-monorepo.sh [options]

Options:
  --project-name NAME           Project directory name (default: multi-platform-project)
  --package-manager PM          npm|pnpm|yarn (default: npm)
  --apps LIST                   Comma-separated: admin,h5,mp,mobile (default: admin,h5,mp,mobile)
  --include-api BOOL            true|false (default: true)
  --mobile-stack TYPE           rn|flutter|native (default: rn)
  --include-openspec BOOL       true|false (default: true)
  --include-github-ci BOOL      true|false (default: true)
  --interactive BOOL            true|false (default: true)
  -h, --help                    Show this help

Examples:
  ./create-monorepo.sh
  ./create-monorepo.sh --interactive false --project-name my-app --package-manager pnpm --apps admin,h5,mp --mobile-stack flutter
EOF
}

PROJECT_NAME="multi-platform-project"
PACKAGE_MANAGER="npm"
APPS="admin,h5,mp,mobile"
INCLUDE_API="true"
MOBILE_STACK="rn"
INCLUDE_OPENSPEC="true"
INCLUDE_GITHUB_CI="true"
INTERACTIVE="true"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-name) PROJECT_NAME="${2:-}"; shift 2 ;;
    --package-manager) PACKAGE_MANAGER="${2:-}"; shift 2 ;;
    --apps) APPS="${2:-}"; shift 2 ;;
    --include-api) INCLUDE_API="${2:-}"; shift 2 ;;
    --mobile-stack) MOBILE_STACK="${2:-}"; shift 2 ;;
    --include-openspec) INCLUDE_OPENSPEC="${2:-}"; shift 2 ;;
    --include-github-ci) INCLUDE_GITHUB_CI="${2:-}"; shift 2 ;;
    --interactive) INTERACTIVE="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

validate_bool() {
  local v="$1"
  [[ "$v" == "true" || "$v" == "false" ]]
}

if [[ "$INTERACTIVE" == "true" ]]; then
  read -r -p "Project name [$PROJECT_NAME]: " input || true
  PROJECT_NAME="${input:-$PROJECT_NAME}"

  read -r -p "Package manager (npm|pnpm|yarn) [$PACKAGE_MANAGER]: " input || true
  PACKAGE_MANAGER="${input:-$PACKAGE_MANAGER}"

  read -r -p "Apps (comma-separated admin,h5,mp,mobile) [$APPS]: " input || true
  APPS="${input:-$APPS}"

  read -r -p "Include API service? (true|false) [$INCLUDE_API]: " input || true
  INCLUDE_API="${input:-$INCLUDE_API}"

  read -r -p "Mobile stack (rn|flutter|native) [$MOBILE_STACK]: " input || true
  MOBILE_STACK="${input:-$MOBILE_STACK}"

  read -r -p "Include OpenSpec folders? (true|false) [$INCLUDE_OPENSPEC]: " input || true
  INCLUDE_OPENSPEC="${input:-$INCLUDE_OPENSPEC}"

  read -r -p "Include GitHub CI template? (true|false) [$INCLUDE_GITHUB_CI]: " input || true
  INCLUDE_GITHUB_CI="${input:-$INCLUDE_GITHUB_CI}"
fi

if [[ "$PACKAGE_MANAGER" != "npm" && "$PACKAGE_MANAGER" != "pnpm" && "$PACKAGE_MANAGER" != "yarn" ]]; then
  echo "Invalid package manager: $PACKAGE_MANAGER"
  exit 1
fi

if [[ "$MOBILE_STACK" != "rn" && "$MOBILE_STACK" != "flutter" && "$MOBILE_STACK" != "native" ]]; then
  echo "Invalid mobile stack: $MOBILE_STACK"
  exit 1
fi

validate_bool "$INCLUDE_API" || { echo "include-api must be true or false"; exit 1; }
validate_bool "$INCLUDE_OPENSPEC" || { echo "include-openspec must be true or false"; exit 1; }
validate_bool "$INCLUDE_GITHUB_CI" || { echo "include-github-ci must be true or false"; exit 1; }

if [[ -e "$PROJECT_NAME" ]]; then
  echo "Path already exists: $PROJECT_NAME"
  exit 1
fi

mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

mkdir -p apps packages scripts
[[ "$INCLUDE_API" == "true" ]] && mkdir -p services/api
[[ "$INCLUDE_OPENSPEC" == "true" ]] && mkdir -p openspec/changes
[[ "$INCLUDE_GITHUB_CI" == "true" ]] && mkdir -p .github/workflows

IFS=',' read -r -a app_array <<< "$APPS"
for app in "${app_array[@]}"; do
  case "$app" in
    admin) mkdir -p apps/admin/src ;;
    h5) mkdir -p apps/h5/src ;;
    mp) mkdir -p apps/mp-wechat/src ;;
    mobile)
      mkdir -p apps/mobile/src
      case "$MOBILE_STACK" in
        rn) mkdir -p apps/mobile/android apps/mobile/ios ;;
        flutter) mkdir -p apps/mobile/lib apps/mobile/android apps/mobile/ios ;;
        native) mkdir -p apps/mobile/android apps/mobile/ios apps/mobile/harmony ;;
      esac
      ;;
    *) echo "Skipping unknown app key: $app" ;;
  esac
done

mkdir -p packages/types/src packages/sdk/src packages/utils/src packages/config

cat > package.json <<EOF
{
  "name": "$PROJECT_NAME",
  "private": true,
  "workspaces": [
    "apps/*",
    "services/*",
    "packages/*"
  ],
  "scripts": {
    "lint": "echo \\\"add lint commands per app\\\"",
    "test": "echo \\\"add test commands per app\\\"",
    "build": "echo \\\"add build commands per app\\\""
  }
}
EOF

cat > README.md <<EOF
# $PROJECT_NAME

Generated by create-monorepo.sh

## Stack choices
- Package manager: $PACKAGE_MANAGER
- Apps: $APPS
- Include API: $INCLUDE_API
- Mobile stack: $MOBILE_STACK
- Include OpenSpec: $INCLUDE_OPENSPEC
- Include GitHub CI: $INCLUDE_GITHUB_CI

## Next steps
1. Install dependencies with your package manager.
2. Add real lint/test/build scripts for each app/service.
3. Add API contract generation into packages/sdk.
4. Add OpenSpec change templates in openspec/changes.
EOF

if [[ "$INCLUDE_GITHUB_CI" == "true" ]]; then
  cat > .github/workflows/ci.yml <<'EOF'
name: monorepo-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      admin: ${{ steps.filter.outputs.admin }}
      h5: ${{ steps.filter.outputs.h5 }}
      mp: ${{ steps.filter.outputs.mp }}
      mobile: ${{ steps.filter.outputs.mobile }}
      api: ${{ steps.filter.outputs.api }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            admin:
              - 'apps/admin/**'
            h5:
              - 'apps/h5/**'
            mp:
              - 'apps/mp-wechat/**'
            mobile:
              - 'apps/mobile/**'
            api:
              - 'services/api/**'
            shared:
              - 'packages/types/**'
              - 'packages/sdk/**'

  admin-ci:
    needs: detect-changes
    if: needs.detect-changes.outputs.admin == 'true' || needs.detect-changes.outputs.shared == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: echo "add admin lint/test/build"
EOF
fi

if [[ "$PACKAGE_MANAGER" == "pnpm" ]]; then
  cat > pnpm-workspace.yaml <<'EOF'
packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
EOF
fi

echo "Project scaffold created at: $PROJECT_NAME"
echo "Tip: chmod +x create-monorepo.sh (for this script itself in source repo)"
